# Generated by Django 4.2 on 2025-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
